import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import store from "./store";
import "bootstrap/dist/js/bootstrap.bundle.js";
import "bootstrap/dist/css/bootstrap.rtl.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import "@/assets/scss/main.scss";
import Countdown from 'vue3-flip-countdown';
import "flickity/dist/flickity.min.css";
import "flickity/dist/flickity.pkgd.js";
createApp(App).use(store).use(router).use(Countdown).mount("#app");
